import '@/styles/globals.css';
import Navbar from '@/components/Navbar';
import { SessionProvider } from 'next-auth/react';
import type { AppProps } from 'next/app';
import { useRouter } from 'next/router';
import Head from 'next/head';

const disableNavbar = ['auth', 'admin', 'member'];

export default function App({ Component, pageProps: { session, ...pageProps } }: AppProps) {
	const { pathname } = useRouter();
	return (
		<SessionProvider session={session}>
			<Head>
				<title>API STORE</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
				<link
					href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css'
					rel='stylesheet'
				></link>
			</Head>
			{!disableNavbar.includes(pathname.split('/')[1]) && <Navbar />}
			<Component {...pageProps} />
		</SessionProvider>
	);
}
